#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : glide
Version  : 0.13.2
Release  : 2
URL      : https://github.com/Masterminds/glide/archive/v0.13.2.tar.gz
Source0  : https://github.com/Masterminds/glide/archive/v0.13.2.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 MIT
Requires: glide-bin = %{version}-%{release}
Requires: glide-license = %{version}-%{release}
BuildRequires : buildreq-golang
BuildRequires : go

%description
# Glide: Vendor Package Management for Golang
![glide logo](https://glide.sh/assets/logo-small.png)

%package bin
Summary: bin components for the glide package.
Group: Binaries
Requires: glide-license = %{version}-%{release}

%description bin
bin components for the glide package.


%package license
Summary: license components for the glide package.
Group: Default

%description license
license components for the glide package.


%prep
%setup -q -n glide-0.13.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1550779520
## make_prepend content
export GOPATH=/go
mkdir -p /go/src/github.com/Masterminds
ln -s /builddir/build/BUILD/glide-0.13.2  /go/src/github.com/Masterminds/glide
pushd /go/src/github.com/Masterminds/glide
## make_prepend end
make  %{?_smp_mflags} build


%install
export SOURCE_DATE_EPOCH=1550779520
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/glide
cp LICENSE %{buildroot}/usr/share/package-licenses/glide/LICENSE
cp vendor/github.com/Masterminds/semver/LICENSE.txt %{buildroot}/usr/share/package-licenses/glide/vendor_github.com_Masterminds_semver_LICENSE.txt
cp vendor/github.com/Masterminds/vcs/LICENSE.txt %{buildroot}/usr/share/package-licenses/glide/vendor_github.com_Masterminds_vcs_LICENSE.txt
cp vendor/github.com/codegangsta/cli/LICENSE %{buildroot}/usr/share/package-licenses/glide/vendor_github.com_codegangsta_cli_LICENSE
cp vendor/github.com/mitchellh/go-homedir/LICENSE %{buildroot}/usr/share/package-licenses/glide/vendor_github.com_mitchellh_go-homedir_LICENSE
cp vendor/gopkg.in/yaml.v2/LICENSE %{buildroot}/usr/share/package-licenses/glide/vendor_gopkg.in_yaml.v2_LICENSE
cp vendor/gopkg.in/yaml.v2/LICENSE.libyaml %{buildroot}/usr/share/package-licenses/glide/vendor_gopkg.in_yaml.v2_LICENSE.libyaml
true
## install_append content
install -d %{buildroot}/usr/bin
install -p -m 755 glide %{buildroot}/usr/bin/glide
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/glide

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/glide/LICENSE
/usr/share/package-licenses/glide/vendor_github.com_Masterminds_semver_LICENSE.txt
/usr/share/package-licenses/glide/vendor_github.com_Masterminds_vcs_LICENSE.txt
/usr/share/package-licenses/glide/vendor_github.com_codegangsta_cli_LICENSE
/usr/share/package-licenses/glide/vendor_github.com_mitchellh_go-homedir_LICENSE
/usr/share/package-licenses/glide/vendor_gopkg.in_yaml.v2_LICENSE
/usr/share/package-licenses/glide/vendor_gopkg.in_yaml.v2_LICENSE.libyaml
